services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=local'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - '4318:4318'
      - '16686:16686'
    environment:
      - 'COLLECTOR_OTLP_ENABLED=true'
  prometheus:
    image: 'prom/prometheus:latest'
    network_mode: host
    volumes:
      - './prometheus:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  loki:
    image: 'grafana/loki:latest'
    network_mode: host
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    image: 'grafana/grafana-enterprise:latest'
    network_mode: host