scrape_configs:
  - job_name: 'Todo Prometheus Scrapper'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'localhost:8081' ]
        labels:
          application: 'Todo Application'
  - job_name: 'postgres'
    static_configs:
      - targets:
          - localhost:5432
    metrics_path: /probe